package com.debthunter.ai;

import static org.assertj.core.api.Assertions.assertThat;

import com.debthunter.domain.Category;
import com.debthunter.domain.Finding;
import com.debthunter.domain.Severity;
import com.sun.net.httpserver.HttpServer;
import java.io.IOException;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.concurrent.atomic.AtomicReference;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;

/**
 * AC-78: {@link FixAgent} opens a pull request via a real source-hosting API call (a local HTTP
 * server standing in for one), with a description that cites the finding id and is labelled as
 * auto-generated.
 */
class AC78_AutoPRCreationTest {

  private HttpServer server;

  @AfterEach
  void stopServer() {
    if (server != null) {
      server.stop(0);
    }
  }

  @Test
  void ac78_aProposedFixOpensAPullRequestCitingTheFindingIdAndLabelledAutoGenerated()
      throws IOException {
    AtomicReference<String> receivedBody = new AtomicReference<>();
    server = HttpServer.create(new InetSocketAddress("127.0.0.1", 0), 0);
    server.createContext(
        "/",
        exchange -> {
          byte[] requestBody = exchange.getRequestBody().readAllBytes();
          receivedBody.set(new String(requestBody, StandardCharsets.UTF_8));
          byte[] body =
              "https://example.invalid/acme/widgets/pulls/42".getBytes(StandardCharsets.UTF_8);
          exchange.sendResponseHeaders(201, body.length);
          try (OutputStream out = exchange.getResponseBody()) {
            out.write(body);
          }
        });
    server.start();

    SourceHostClient client =
        new HttpSourceHostClient(
            URI.create("http://127.0.0.1:" + server.getAddress().getPort()),
            null,
            Duration.ofSeconds(5));
    FixAgent agent = new FixAgent(client, repository -> true);

    PullRequestResult result = agent.proposeFix(finding(), "acme/widgets", "main");

    assertThat(result.created()).isTrue();
    assertThat(result.pullRequestUrl()).isEqualTo("https://example.invalid/acme/widgets/pulls/42");
    String body = receivedBody.get();
    assertThat(body).contains("f-1").contains("auto-generated");
  }

  private Finding finding() {
    return Finding.builder()
        .id("f-1")
        .ruleId("hotspot.rule")
        .category(Category.HOTSPOT)
        .severity(Severity.HIGH)
        .path("Foo.java")
        .message("Foo.java changes often")
        .fingerprint("fp-1")
        .build();
  }
}
