package com.debthunter.ai;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.debthunter.domain.Category;
import com.debthunter.domain.Finding;
import com.debthunter.domain.Severity;
import java.util.concurrent.atomic.AtomicReference;
import org.junit.jupiter.api.Test;

class FixAgentTest {

  @Test
  void proposeFixOpensAPullRequestWithAGeneratedPatchAndAutoGeneratedLabels() {
    AtomicReference<PullRequestRequest> captured = new AtomicReference<>();
    SourceHostClient client = mock(SourceHostClient.class);
    when(client.openPullRequest(any()))
        .thenAnswer(
            invocation -> {
              captured.set(invocation.getArgument(0));
              return PullRequestResult.created("https://example.invalid/pulls/1");
            });
    FixAgent agent = new FixAgent(client, alwaysAllow());

    PullRequestResult result = agent.proposeFix(finding(), "acme/widgets", "main");

    assertThat(result.created()).isTrue();
    assertThat(result.pullRequestUrl()).isEqualTo("https://example.invalid/pulls/1");
    PullRequestRequest request = captured.get();
    assertThat(request.repository()).isEqualTo("acme/widgets");
    assertThat(request.baseBranch()).isEqualTo("main");
    assertThat(request.branchName()).isEqualTo("debt-hunter/fix-f-1");
    assertThat(request.labels()).contains("auto-generated");
    assertThat(request.description()).contains("f-1");
    assertThat(request.patch()).contains("Foo.java").contains("f-1");
  }

  @Test
  void aRateLimitedRepositoryIsRejectedWithoutCallingTheSourceHost() {
    SourceHostClient client = mock(SourceHostClient.class);
    FixAgent agent = new FixAgent(client, repository -> false);

    PullRequestResult result = agent.proposeFix(finding(), "acme/widgets", "main");

    assertThat(result.created()).isFalse();
    assertThat(result.reason()).contains("acme/widgets");
    verify(client, never()).openPullRequest(any());
  }

  @Test
  void aRejectedSourceHostResponseIsNotAugmented() {
    SourceHostClient client = mock(SourceHostClient.class);
    when(client.openPullRequest(any())).thenReturn(PullRequestResult.rejected("HTTP 422"));
    FixAgent agent = new FixAgent(client, alwaysAllow());

    PullRequestResult result = agent.proposeFix(finding(), "acme/widgets", "main");

    assertThat(result.created()).isFalse();
    assertThat(result.reason()).isEqualTo("HTTP 422");
  }

  private FixAgentRateLimiter alwaysAllow() {
    return repository -> true;
  }

  private Finding finding() {
    return Finding.builder()
        .id("f-1")
        .ruleId("hotspot.rule")
        .category(Category.HOTSPOT)
        .severity(Severity.HIGH)
        .path("Foo.java")
        .message("Foo.java changes often")
        .fingerprint("fp-1")
        .build();
  }
}
